//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEFI_SyO_Mascotas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascotas
    {
        public int Id_Mascota { get; set; }
        public string Nombre_Mascota { get; set; }
        public string Apodo_Mascota { get; set; }
        public Nullable<int> Id_Raza { get; set; }
        public Nullable<int> Id_Propietario { get; set; }
    
        public virtual Propietarios_Mascotas Propietarios_Mascotas { get; set; }
        public virtual Razas Razas { get; set; }
    }
}
