//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IefiSistemas2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        public int Id_Mascota { get; set; }
        public string Nombre_Mascota { get; set; }
        public string Apodo { get; set; }
        public string Nombre_Dueño { get; set; }
        public Nullable<int> Id_Raza { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    
        public virtual Raza Raza { get; set; }
    }
}
